package jcf;

/**
 * Base Enum for Application Roles.
 * Automatically managed and regenerated by JettraAppServer based on jettra-config.properties.
 */
public enum AppRole {
    ADMIN,
    MANAGER,
    USER;

    public String getValue() {
        return name();
    }
}
