package io.jettra.flux.annotations.crud;

import io.jettra.flux.annotations.FieldMetadata;
import java.util.List;
import java.util.Map;

/**
 * Interface generated by Annotation Processor to handle CRUD operations without reflection.
 */
public interface RenderedCrudHandler<M> {
    List<M> findAll();
    void save(M model);
    void delete(String id);
    String getIdValue(M item);
    Map<String, String> getJsonMap(M item);
    M createInstance();
    void updateFields(M model, Map<String, String> data);
    
    // UI Metadata & Reflection-free access
    List<FieldMetadata> getFieldsMetadata();
    Object getFieldValue(M item, String fieldName);
    void setFieldValue(M item, String fieldName, Object value);
    Object getNestedFieldValue(Object item, String fieldName);
    void setNestedFieldValue(Object item, String fieldName, Object value);
   FieldMetadata getNestedFieldMetadata(Object item, String fieldName);
}
