app.title=JettraEE Server
app.shorttitle=JEE
server.port=8080
server.contextpath=/
server.compactheader=true
server.session.timeout=0
app.language=es
app.theme=sai
app.animated=false
server.hotreload=false
server.JWT_SECRET=default_secret_key_jettra_ee_2026
server.JWT_EXPIRATION=86400000
server.consoleshowregisterpage=false
app.roles=ADMIN,MANAGER,USER
