jettra.rest.base-path=
jettra.rest.security.jwt.secret=default_secret_key_jettra_ee_2026
jettra.rest.security.jwt.expiration-millis=86400000
jettra.rest.security.header-name=Authorization
jettra.rest.security.token-prefix=Bearer 
