package io.jettra.flux.theme;

/**
 * CoreTheme provides an authentic sci-fi HUD and 3D virtual environment aesthetic
 * modeled directly after Jettra 3D Core - Java 25 Native:
 *
 * Visual Signature:
 * - Jettra Core Amber Gold (#f59e0b / #fbbf24) primary brand & HUD header color
 * - Java 25 Edition Sky Blue / Cyan (#38bdf8 / #00e5ff) sub-headers & metric accents
 * - Deep 3D Space Black canvas (#0b0e14) with subtle perspective grid lines
 * - Dark HUD Glass Surfaces (rgba(16, 22, 33, 0.94) / #121824)
 * - Distinctive Jettra Core GUI action buttons (Crimson Reset, Lime Save, Cyan Config, Slate Director, Purple Chat)
 * - Sharp HUD bounding boxes with gold borders and techno-monospace telemetry logs
 */
public class CoreTheme {

    public static ThemeData create() {
        return Core.create();
    }

    public static ThemeData create(ColorMode mode) {
        return Core.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return Core.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* CoreTheme - Jettra 3D Core HUD Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500;600;700;800;900&family=Rajdhani:wght@500;600;700&family=Share+Tech+Mono&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --core-gold: #f59e0b;\n"
            + "  --core-gold-hover: #fbbf24;\n"
            + "  --core-skyblue: #38bdf8;\n"
            + "  --core-lime: #22c55e;\n"
            + "  --core-red: #ef4444;\n"
            + "  --core-purple: #a855f7;\n"
            + "  --core-dark-bg: #0b0e14;\n"
            + "  --core-hud-surface: rgba(16, 22, 33, 0.94);\n"
            + "  --core-border-gold: #f59e0b;\n"
            + "  --core-border-slate: rgba(255, 255, 255, 0.2);\n"
            + "  --background-color: #0b0e14 !important;\n"
            + "  --surface-color: #161f2e !important;\n"
            + "  --on-surface-color: #f1f5f9 !important;\n"
            + "  --on-primary-color: #0b0e14 !important;\n"
            + "  --primary-color: #f59e0b !important;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "/* Preserve icon font families */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "}\n"
            + "\n"
            + "/* 3D Core Space Grid Background */\n"
            + "html, body {\n"
            + "  background-color: #0b0e14 !important;\n"
            + "  background-image:\n"
            + "    radial-gradient(ellipse at 50% 10%, rgba(56, 189, 248, 0.08) 0%, transparent 60%),\n"
            + "    radial-gradient(ellipse at 50% 90%, rgba(245, 158, 11, 0.06) 0%, transparent 60%),\n"
            + "    linear-gradient(to right, rgba(255, 255, 255, 0.04) 1px, transparent 1px),\n"
            + "    linear-gradient(to bottom, rgba(255, 255, 255, 0.04) 1px, transparent 1px) !important;\n"
            + "  background-size: 100% 100%, 100% 100%, 36px 36px, 36px 36px !important;\n"
            + "  background-attachment: fixed !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "}\n"
            + "\n"
            + "/* Core Custom Amber/Slate Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #0b0e14; }\n"
            + "::-webkit-scrollbar-thumb { background: #1e293b; border-radius: 4px; border: 1px solid rgba(245, 158, 11, 0.35); }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #f59e0b; box-shadow: 0 0 8px #f59e0b; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard, .espresso-center, .espresso-main, .jettra-main-viewport, .professional-center {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + ".espresso-top, .jettra-topbar {\n"
            + "  background: rgba(16, 22, 33, 0.95) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-bottom: 1px solid #f59e0b !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.6), 0 0 15px rgba(245, 158, 11, 0.1) !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  z-index: 10;\n"
            + "}\n"
            + ".espresso-left, .jettra-drawer {\n"
            + "  background: rgba(14, 19, 29, 0.96) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-right: 1px solid rgba(245, 158, 11, 0.35) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  z-index: 5;\n"
            + "}\n"
            + ".espresso-footer {\n"
            + "  background: rgba(16, 22, 33, 0.95) !important;\n"
            + "  border-top: 1px solid rgba(245, 158, 11, 0.25) !important;\n"
            + "  color: #94a3b8 !important;\n"
            + "  display: flex;\n"
            + "  justify-content: center;\n"
            + "  align-items: center;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Brand & HUD Title */\n"
            + ".sidebar-logo {\n"
            + "  color: #f59e0b !important;\n"
            + "  font-family: 'Orbitron', 'Rajdhani', sans-serif !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 1.3rem;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  text-transform: uppercase;\n"
            + "  text-shadow: 0 0 10px rgba(245, 158, 11, 0.5);\n"
            + "}\n"
            + ".sidebar-category {\n"
            + "  color: #38bdf8 !important;\n"
            + "  font-family: 'Rajdhani', 'Share Tech Mono', sans-serif !important;\n"
            + "  font-size: 0.8rem;\n"
            + "  font-weight: 700;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.15em;\n"
            + "}\n"
            + "\n"
            + "/* Navigation Links (HUD Command Style) */\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #94a3b8 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 600;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-size: 1.05rem;\n"
            + "  letter-spacing: 0.04em;\n"
            + "  border: 1px solid transparent;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(245, 158, 11, 0.12) !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  border-color: rgba(245, 158, 11, 0.3) !important;\n"
            + "  transform: translateX(4px);\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background: linear-gradient(90deg, rgba(245, 158, 11, 0.25) 0%, rgba(56, 189, 248, 0.15) 100%) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-left: 3px solid #f59e0b !important;\n"
            + "  border-color: rgba(245, 158, 11, 0.5) !important;\n"
            + "  font-weight: 700;\n"
            + "  box-shadow: 0 0 14px rgba(245, 158, 11, 0.2);\n"
            + "}\n"
            + ".professional-left i, .espresso-left i, .top-right-section i, .jettra-hamburger {\n"
            + "  color: #f59e0b !important;\n"
            + "}\n"
            + ".professional-left a.active i, .espresso-left a.active i {\n"
            + "  color: #f59e0b !important;\n"
            + "  text-shadow: 0 0 8px #f59e0b;\n"
            + "}\n"
            + "\n"
            + "/* Jettra Core Action Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background-color: #f59e0b !important;\n"
            + "  color: #0b0e14 !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.35) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  font-family: 'Rajdhani', 'Share Tech Mono', sans-serif !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  box-shadow: 0 0 12px rgba(245, 158, 11, 0.35) !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-button *, .espresso-btn *, .btn *, .btn-primary * {\n"
            + "  color: #0b0e14 !important;\n"
            + "  font-weight: 700 !important;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background-color: #fbbf24 !important;\n"
            + "  box-shadow: 0 0 18px rgba(245, 158, 11, 0.6) !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  border: 1px solid #f59e0b !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-btn-outlined *, .btn-outline-primary * {\n"
            + "  color: #f59e0b !important;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: rgba(245, 158, 11, 0.18) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-color: #fbbf24 !important;\n"
            + "  box-shadow: 0 0 14px rgba(245, 158, 11, 0.4) !important;\n"
            + "}\n"
            + ".espresso-btn-secondary, .espresso-btn-secondary * {\n"
            + "  background-color: #334155 !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.25) !important;\n"
            + "}\n"
            + ".espresso-btn-danger, .espresso-btn-danger * {\n"
            + "  background-color: #b91c1c !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.35) !important;\n"
            + "  box-shadow: 0 0 10px rgba(239, 68, 68, 0.35) !important;\n"
            + "}\n"
            + ".espresso-btn-success, .espresso-btn-success * {\n"
            + "  background-color: #15803d !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.35) !important;\n"
            + "  box-shadow: 0 0 10px rgba(34, 197, 94, 0.35) !important;\n"
            + "}\n"
            + ".espresso-btn-info, .espresso-btn-info * {\n"
            + "  background-color: #0284c7 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.35) !important;\n"
            + "  box-shadow: 0 0 10px rgba(56, 189, 248, 0.35) !important;\n"
            + "}\n"
            + ".espresso-btn-help, .espresso-btn-help * {\n"
            + "  background-color: #7e22ce !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.35) !important;\n"
            + "  box-shadow: 0 0 10px rgba(168, 85, 247, 0.35) !important;\n"
            + "}\n"
            + "\n"
            + "/* HUD Cards & Panels */\n"
            + ".espresso-card, .card, .espresso-panel,\n"
            + "[class*=\"bg-white\"], [class*=\"bg-light\"], .bg-white, .bg-light {\n"
            + "  background-color: rgba(16, 22, 33, 0.94) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid #f59e0b !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.8), inset 0 0 15px rgba(245, 158, 11, 0.05) !important;\n"
            + "  padding: 24px;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + ".espresso-card:hover, .card:hover {\n"
            + "  border-color: #fbbf24 !important;\n"
            + "  box-shadow: 0 0 20px rgba(245, 158, 11, 0.25) !important;\n"
            + "}\n"
            + ".espresso-panel-header {\n"
            + "  background: rgba(11, 15, 23, 0.95) !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  border-bottom: 1px solid rgba(245, 158, 11, 0.3) !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-size: 1.1rem;\n"
            + "  font-weight: 700;\n"
            + "  padding: 14px 20px;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  text-transform: uppercase;\n"
            + "}\n"
            + "\n"
            + "/* Headings & Text */\n"
            + "h1, h2, h3, h4, h5, h6, .top-dashboard-title, .stat-value, .chart-card-header, strong, b {\n"
            + "  color: #f59e0b !important;\n"
            + "  font-family: 'Orbitron', 'Rajdhani', sans-serif !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  letter-spacing: 0.05em;\n"
            + "}\n"
            + "p, span, label, td, li, .tx-details, .stat-header, .tx-date {\n"
            + "  color: #cbd5e1;\n"
            + "}\n"
            + "small {\n"
            + "  color: #94a3b8 !important;\n"
            + "}\n"
            + ".text-dark, .text-black, [class*=\"text-dark\"], [class*=\"text-black\"] {\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber,\n"
            + ".form-control, .form-select, input, textarea, select {\n"
            + "  background-color: #0f1521 !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid rgba(245, 158, 11, 0.4) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px;\n"
            + "  font-size: 14px;\n"
            + "  font-family: 'Inter', sans-serif;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus,\n"
            + ".form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #f59e0b !important;\n"
            + "  box-shadow: 0 0 0 3px rgba(245, 158, 11, 0.25), 0 0 12px rgba(245, 158, 11, 0.3) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: #64748b !important;\n"
            + "}\n"
            + "option, select option {\n"
            + "  background-color: #0f1521 !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + "\n"
            + "/* HUD Datatables */\n"
            + ".espresso-datatable, .espresso-table, .table, table {\n"
            + "  background-color: rgba(16, 22, 33, 0.95) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid rgba(245, 158, 11, 0.3) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th, thead th {\n"
            + "  background-color: #0d121c !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  border-bottom: 2px solid #f59e0b !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.85rem;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "  padding: 12px 16px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td, tbody td {\n"
            + "  border-bottom: 1px solid rgba(255, 255, 255, 0.06) !important;\n"
            + "  color: #cbd5e1 !important;\n"
            + "  background-color: transparent !important;\n"
            + "  padding: 14px 16px;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(245, 158, 11, 0.08) !important;\n"
            + "}\n"
            + "\n"
            + "/* HUD Badges & Chips */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag {\n"
            + "  background-color: rgba(245, 158, 11, 0.15) !important;\n"
            + "  color: #f59e0b !important;\n"
            + "  border: 1px solid rgba(245, 158, 11, 0.4) !important;\n"
            + "  border-radius: 4px !important;\n"
            + "  padding: 3px 8px;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-family: 'Share Tech Mono', monospace !important;\n"
            + "}\n"
            + "\n"
            + "/* HUD Alerts */\n"
            + ".espresso-alert {\n"
            + "  border-radius: 6px !important;\n"
            + "  background-color: rgba(14, 19, 29, 0.95) !important;\n"
            + "  box-shadow: 0 4px 15px rgba(0,0,0,0.5) !important;\n"
            + "}\n"
            + ".espresso-alert-danger { border-left: 4px solid #ef4444 !important; color: #fca5a5 !important; background-color: rgba(239, 68, 68, 0.12) !important; }\n"
            + ".espresso-alert-success { border-left: 4px solid #22c55e !important; color: #86efac !important; background-color: rgba(34, 197, 94, 0.12) !important; }\n"
            + ".espresso-alert-info { border-left: 4px solid #38bdf8 !important; color: #7dd3fc !important; background-color: rgba(56, 189, 248, 0.12) !important; }\n"
            + "\n"
            + "/* HUD Modals & Dialogs */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content, .modal {\n"
            + "  background-color: rgba(14, 20, 30, 0.98) !important;\n"
            + "  border: 1px solid #f59e0b !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 0 30px rgba(0, 0, 0, 0.8), 0 0 15px rgba(245, 158, 11, 0.2) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + "\n"
            + "/* Dropdowns */\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: rgba(16, 22, 33, 0.96) !important;\n"
            + "  border: 1px solid rgba(245, 158, 11, 0.4) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.7) !important;\n"
            + "  color: #cbd5e1 !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #cbd5e1 !important;\n"
            + "  padding: 10px 16px;\n"
            + "  border-radius: 4px;\n"
            + "  transition: all 0.15s ease;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: rgba(245, 158, 11, 0.18) !important;\n"
            + "  color: #f59e0b !important;\n"
            + "}\n"
            + "\n"
            + "/* Tabs & Accordions */\n"
            + ".espresso-tabview-nav { border-bottom: 2px solid rgba(245, 158, 11, 0.3) !important; }\n"
            + ".espresso-tabview-nav-link { color: #94a3b8 !important; }\n"
            + ".espresso-tabview-nav-link:hover { color: #ffffff !important; }\n"
            + ".espresso-tabview-nav-active .espresso-tabview-nav-link { color: #f59e0b !important; border-bottom: 2px solid #f59e0b !important; }\n"
            + ".espresso-divider-content { background-color: #161f2e !important; color: #94a3b8 !important; }\n"
            + ".espresso-divider { border-color: rgba(245, 158, 11, 0.3) !important; }\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "function toggleSidebar() {\n"
            + "  var sidebar = document.querySelector('.espresso-left');\n"
            + "  if(sidebar) sidebar.classList.toggle('open');\n"
            + "}\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".core-dashboard-grid, .oceantheme-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".core-main-grid, .oceantheme-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .core-dashboard-grid, .core-main-grid, .oceantheme-dashboard-grid, .oceantheme-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: rgba(16, 22, 33, 0.94) !important; border: 1px solid #f59e0b !important; border-radius: 8px !important; box-shadow: 0 4px 20px rgba(0,0,0,0.8), inset 0 0 15px rgba(245,158,11,0.05) !important; padding: 22px; }\n"
            + ".stat-header { font-size: 0.85rem; color: #38bdf8 !important; font-weight: 700; font-family: 'Rajdhani', sans-serif !important; text-transform: uppercase; letter-spacing: 0.08em; }\n"
            + ".stat-value { font-size: 2.2rem; font-weight: 800; color: #f59e0b !important; font-family: 'Orbitron', sans-serif !important; }\n"
            + ".stat-badge { padding: 4px 10px; border-radius: 4px; font-size: 0.75rem; font-weight: 700; display: inline-flex; align-items: center; gap: 4px; font-family: 'Share Tech Mono', monospace; }\n"
            + ".stat-badge.down { background-color: rgba(239, 68, 68, 0.15) !important; color: #f87171 !important; border: 1px solid rgba(239, 68, 68, 0.3) !important; }\n"
            + ".stat-badge.up { background-color: rgba(34, 197, 94, 0.15) !important; color: #4ade80 !important; border: 1px solid rgba(34, 197, 94, 0.35) !important; }\n"
            + "</style>";
    }
}
