package io.jettra.flux.theme;

/**
 * HeroesTheme provides a dark marketing hero aesthetic based on Flowbite Dark Mode
 * and Tailwind UI Heroes.
 *
 * Combines Flowbite Dark (#111827 / #1f2937) with subtle ambient hero mesh glow
 * and Tailwind Indigo 600 (#4f46e5) primary actions.
 */
public class HeroesTheme {

    public static ThemeData create() {
        return Heroes.create();
    }

    public static ThemeData create(ColorMode mode) {
        return Heroes.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return Heroes.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* HeroesTheme Dark Flowbite Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --hero-primary: #4f46e5;\n"
            + "  --hero-primary-hover: #4338ca;\n"
            + "  --hero-rose: #ff80b5;\n"
            + "  --hero-indigo: #9089fc;\n"
            + "  --hero-gray-900: #111827;\n"
            + "  --hero-gray-800: #1f2937;\n"
            + "  --hero-gray-700: #374151;\n"
            + "  --hero-gray-600: #4b5563;\n"
            + "  --hero-gray-400: #9ca3af;\n"
            + "  --hero-gray-200: #e5e7eb;\n"
            + "  --background-color: #111827 !important;\n"
            + "  --surface-color: #1f2937 !important;\n"
            + "  --on-surface-color: #f9fafb !important;\n"
            + "  --on-primary-color: #ffffff !important;\n"
            + "  --primary-color: #4f46e5 !important;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "/* Preserve icon font families */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "}\n"
            + "\n"
            + "/* Body with Flowbite Dark & Subtle Ambient Hero Glow */\n"
            + "html, body {\n"
            + "  background-color: #111827 !important;\n"
            + "  background-image: \n"
            + "    radial-gradient(at 12% 12%, rgba(255, 128, 181, 0.08) 0px, transparent 50%),\n"
            + "    radial-gradient(at 88% 16%, rgba(144, 137, 252, 0.12) 0px, transparent 55%),\n"
            + "    radial-gradient(at 50% 90%, rgba(79, 70, 229, 0.07) 0px, transparent 50%) !important;\n"
            + "  background-attachment: fixed !important;\n"
            + "  color: #f9fafb !important;\n"
            + "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;\n"
            + "  letter-spacing: -0.015em;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "}\n"
            + "\n"
            + "/* Dark Custom Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #111827; }\n"
            + "::-webkit-scrollbar-thumb { background: #374151; border-radius: 4px; }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #4b5563; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard, .espresso-center, .espresso-main, .jettra-main-viewport, .professional-center {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f9fafb !important;\n"
            + "}\n"
            + ".espresso-top, .jettra-topbar {\n"
            + "  background: rgba(31, 41, 55, 0.9) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-bottom: 1px solid #374151 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  z-index: 10;\n"
            + "}\n"
            + ".espresso-left, .jettra-drawer {\n"
            + "  background: rgba(31, 41, 55, 0.95) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-right: 1px solid #374151 !important;\n"
            + "  color: #f9fafb !important;\n"
            + "  z-index: 5;\n"
            + "}\n"
            + ".espresso-footer {\n"
            + "  background: #1f2937 !important;\n"
            + "  border-top: 1px solid #374151 !important;\n"
            + "  color: #9ca3af !important;\n"
            + "  display: flex;\n"
            + "  justify-content: center;\n"
            + "  align-items: center;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Brand & Links */\n"
            + ".sidebar-logo {\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  letter-spacing: -0.025em;\n"
            + "}\n"
            + ".sidebar-category {\n"
            + "  color: #9ca3af !important;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-weight: 700;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "}\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #9ca3af !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 500;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  transform: translateX(3px);\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background-color: #4f46e5 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 600;\n"
            + "}\n"
            + ".professional-left i, .espresso-left i, .top-right-section i, .jettra-hamburger {\n"
            + "  color: #9ca3af !important;\n"
            + "}\n"
            + ".professional-left a.active i, .espresso-left a.active i {\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Hero Announcement Pill (Dark Translucent) */\n"
            + ".hero-pill, .espresso-pill-badge {\n"
            + "  display: inline-flex;\n"
            + "  align-items: center;\n"
            + "  gap: 8px;\n"
            + "  padding: 4px 14px;\n"
            + "  border-radius: 9999px;\n"
            + "  background: rgba(55, 65, 81, 0.7);\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.12);\n"
            + "  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2);\n"
            + "  font-size: 0.875rem;\n"
            + "  color: #e5e7eb;\n"
            + "  backdrop-filter: blur(8px);\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".hero-pill:hover {\n"
            + "  border-color: rgba(255, 255, 255, 0.25);\n"
            + "}\n"
            + "\n"
            + "/* Buttons (Indigo 600) */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background-color: #4f46e5 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: none !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 20px !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2) !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: background-color 0.2s, transform 0.15s;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background-color: #4338ca !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + ".espresso-btn-secondary {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #e5e7eb !important;\n"
            + "  border: 1px solid #4b5563 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #a5b4fc !important;\n"
            + "  border: 1px solid #4f46e5 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 20px !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: #4f46e5 !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Dark Flowbite Cards & Panels */\n"
            + ".espresso-card, .card, .espresso-panel,\n"
            + "[class*=\"bg-white\"], [class*=\"bg-light\"], .bg-white, .bg-light {\n"
            + "  background-color: #1f2937 !important;\n"
            + "  color: #f9fafb !important;\n"
            + "  border: 1px solid #374151 !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.3) !important;\n"
            + "  padding: 24px;\n"
            + "}\n"
            + ".espresso-panel-header {\n"
            + "  background-color: #111827 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-bottom: 1px solid #374151 !important;\n"
            + "  font-weight: 700;\n"
            + "  padding: 14px 20px;\n"
            + "}\n"
            + "\n"
            + "/* Headings & Text */\n"
            + "h1, h2, h3, h4, h5, h6, .top-dashboard-title, .stat-value, .chart-card-header, strong, b {\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  letter-spacing: -0.025em;\n"
            + "}\n"
            + "p, span, label, td, li, .tx-details, .stat-header, .tx-date {\n"
            + "  color: #e5e7eb;\n"
            + "  line-height: 1.6;\n"
            + "}\n"
            + "small {\n"
            + "  color: #9ca3af !important;\n"
            + "}\n"
            + ".text-dark, .text-black, [class*=\"text-dark\"], [class*=\"text-black\"] {\n"
            + "  color: #f9fafb !important;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber,\n"
            + ".form-control, .form-select, input, textarea, select {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid #4b5563 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 14px;\n"
            + "  font-size: 14px;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus,\n"
            + ".form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #4f46e5 !important;\n"
            + "  box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.3) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: #9ca3af !important;\n"
            + "}\n"
            + "option, select option {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Tables */\n"
            + ".espresso-datatable, .espresso-table, .table, table {\n"
            + "  background-color: #1f2937 !important;\n"
            + "  color: #f9fafb !important;\n"
            + "  border: 1px solid #374151 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th, thead th {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #9ca3af !important;\n"
            + "  border-bottom: 1px solid #4b5563 !important;\n"
            + "  font-weight: 600;\n"
            + "  font-size: 0.75rem;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  padding: 12px 16px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td, tbody td {\n"
            + "  border-bottom: 1px solid #374151 !important;\n"
            + "  color: #e5e7eb !important;\n"
            + "  background-color: transparent !important;\n"
            + "  padding: 14px 16px;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: #2e3b4e !important;\n"
            + "}\n"
            + "\n"
            + "/* Badges */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag {\n"
            + "  background-color: rgba(79, 70, 229, 0.2) !important;\n"
            + "  color: #a5b4fc !important;\n"
            + "  border: 1px solid rgba(79, 70, 229, 0.35) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 3px 8px;\n"
            + "  font-weight: 600;\n"
            + "  font-size: 0.75rem;\n"
            + "}\n"
            + "\n"
            + "/* Modals & Dropdowns */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content, .modal {\n"
            + "  background-color: #1f2937 !important;\n"
            + "  border: 1px solid #374151 !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5) !important;\n"
            + "  color: #f9fafb !important;\n"
            + "}\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: #1f2937 !important;\n"
            + "  border: 1px solid #374151 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.4) !important;\n"
            + "  color: #e5e7eb !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #e5e7eb !important;\n"
            + "  padding: 10px 16px;\n"
            + "  border-radius: 6px;\n"
            + "  transition: all 0.15s ease;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: #374151 !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Tabs, Accordions, Dividers */\n"
            + ".espresso-tabview-nav { border-bottom: 2px solid #374151 !important; }\n"
            + ".espresso-tabview-nav-link { color: #9ca3af !important; }\n"
            + ".espresso-tabview-nav-link:hover { color: #ffffff !important; }\n"
            + ".espresso-tabview-nav-active .espresso-tabview-nav-link { color: #4f46e5 !important; border-bottom: 2px solid #4f46e5 !important; }\n"
            + ".espresso-divider-content { background-color: #1f2937 !important; color: #9ca3af !important; }\n"
            + ".espresso-divider { border-color: #374151 !important; }\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "function toggleSidebar() {\n"
            + "  var sidebar = document.querySelector('.espresso-left');\n"
            + "  if(sidebar) sidebar.classList.toggle('open');\n"
            + "}\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".heroes-dashboard-grid, .oceantheme-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".heroes-main-grid, .oceantheme-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .heroes-dashboard-grid, .heroes-main-grid, .oceantheme-dashboard-grid, .oceantheme-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: #1f2937 !important; border: 1px solid #374151 !important; border-radius: 12px !important; box-shadow: 0 1px 3px 0 rgba(0,0,0,0.3) !important; padding: 22px; }\n"
            + ".stat-header { font-size: 0.85rem; color: #9ca3af !important; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }\n"
            + ".stat-value { font-size: 2rem; font-weight: 800; color: #ffffff !important; letter-spacing: -0.025em; }\n"
            + ".stat-badge { padding: 4px 10px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; display: inline-flex; align-items: center; gap: 4px; }\n"
            + ".stat-badge.down { background-color: #7f1d1d !important; color: #fca5a5 !important; border: 1px solid #dc2626 !important; }\n"
            + ".stat-badge.up { background-color: #064e3b !important; color: #6ee7b7 !important; border: 1px solid #059669 !important; }\n"
            + "</style>";
    }
}
