package io.jettra.flux.theme;

/**
 * MatrixTheme provides an authentic cyberpunk/Matrix-inspired visual theme for JettraFlux.
 * Modeled directly after the CyberShield / Matrix aesthetic:
 * - Subtle green dot-matrix grid background with CRT scanlines
 * - Razor-sharp, high-legibility terminal monospace typography ('Courier Prime', 'JetBrains Mono')
 * - Electric phosphor Matrix hacker green (#00ff41 / #00ff00)
 * - Deep terminal dark backgrounds (#080c09 / #0a0e0a)
 * - Service/dashboard cards with dark gradient (#101912 to #0a110c), rounded borders (12px), and icon badges
 * - Glowing active/hover state with bright green border (#00ff41) and box-shadow
 * - Navigation links in <TAG/> uppercase format with white hover transitions
 */
public class MatrixTheme implements ThemeDefinition {

    private static final MatrixTheme INSTANCE = new MatrixTheme();

    public static MatrixTheme getInstance() {
        return INSTANCE;
    }

    @Override
    public String getThemeName() {
        return "Matrix";
    }

    @Override
    public ThemeTokens tokens(ColorMode mode) {
        return getTokens(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        if (mode == ColorMode.WHITE) {
            return new ThemeTokens(
                "#f0fdf4",                  // surfaceBackground: light matrix phosphor canvas
                "#ffffff",                  // cardBackground: pure white terminal card
                "#0f3e1a",                  // textPrimary: deep phosphor terminal green (WCAG contrast > 11:1)
                "#166534",                  // textSecondary: forest terminal green (WCAG contrast > 7:1)
                "#86efac",                  // border: neon green border
                "#15803d",                  // accentPrimary: crisp terminal green
                "#16a34a",                  // accentSecondary: matrix phosphor green
                "rgba(21, 128, 61, 0.4)",   // focusRing
                "#15803d"                   // iconColor
            );
        } else {
            return new ThemeTokens(
                "#020b02",                  // surfaceBackground: Deep Matrix Abyss Black
                "#0a120b",                  // cardBackground: Dark Matrix Terminal Surface
                "#00ff66",                  // textPrimary: Crisp phosphor green (WCAG contrast > 15:1)
                "#008f11",                  // textSecondary: Matrix Terminal Green (WCAG contrast > 5:1)
                "rgba(0, 255, 65, 0.25)",   // border: Phosphor green border
                "#00ff41",                  // accentPrimary: Electric Matrix Hacker Green
                "#00ffcc",                  // accentSecondary: Cyan-green glow
                "rgba(0, 255, 65, 0.4)",    // focusRing
                "#00ff41"                   // iconColor
            );
        }
    }

    public static ThemeData create() {
        return create(ColorMode.DARK);
    }

    @Override
    public ThemeData createTheme(ColorMode mode) {
        return create(mode);
    }

    public static ThemeData create(ColorMode mode) {
        ThemeTokens tok = getTokens(mode);
        if (mode == ColorMode.WHITE) {
            return new ThemeData(
                tok.accentPrimary(),
                tok.accentSecondary(),
                tok.surfaceBackground(),
                tok.cardBackground(),
                "#ffffff",
                tok.textPrimary(),
                "border: 1px solid #15803d; border-radius: 6px; padding: 10px 22px; font-weight: 700; font-family: 'Courier Prime', 'JetBrains Mono', 'Courier New', monospace; color: #ffffff; background-color: #15803d; box-shadow: 0 2px 8px rgba(21, 128, 61, 0.25); cursor: pointer; text-transform: uppercase; letter-spacing: 0.1em; transition: all 0.25s ease;",
                "border: 1px solid #86efac; border-radius: 12px; padding: 24px; background: #ffffff; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.06); color: " + tok.textPrimary() + ";",
                "padding: 20px; border-radius: 12px; border: 1px solid #86efac; background-color: #f0fdf4;",
                "font-size: 15px; color: " + tok.textPrimary() + "; font-family: 'Courier Prime', 'JetBrains Mono', 'Courier New', monospace; line-height: 1.65; letter-spacing: 0.03em;",
                Template.CustomCSS,
                Template.CustomJS,
                tok,
                mode
            );
        } else {
            return new ThemeData(
                tok.accentPrimary(),
                tok.accentSecondary(),
                tok.surfaceBackground(),
                tok.cardBackground(),
                "#000000",
                tok.textPrimary(),
                "border: 1px solid #00ff41; border-radius: 6px; padding: 10px 22px; font-weight: 700; font-family: 'Courier Prime', 'JetBrains Mono', 'Courier New', monospace; color: #050a05; background-color: #00ff41; box-shadow: 0 0 14px rgba(0, 255, 65, 0.4); cursor: pointer; text-transform: uppercase; letter-spacing: 0.1em; transition: all 0.25s ease;",
                "border: 1px solid rgba(0, 255, 65, 0.25); border-radius: 12px; padding: 24px; background: linear-gradient(180deg, #101912 0%, #09100a 100%); box-shadow: 0 4px 20px rgba(0, 0, 0, 0.7); color: #00ff66;",
                "padding: 20px; border-radius: 12px; border: 1px solid rgba(0, 255, 65, 0.25); background-color: rgba(9, 16, 10, 0.92); box-shadow: 0 4px 20px rgba(0, 0, 0, 0.6);",
                "font-size: 15px; color: #00ff66; font-family: 'Courier Prime', 'JetBrains Mono', 'Courier New', monospace; line-height: 1.65; letter-spacing: 0.03em;",
                Template.CustomCSS,
                Template.CustomJS,
                tok,
                mode
            );
        }
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* Matrix Theme Global Enhancements (CyberShield & Matrix Film Aesthetic) */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&family=JetBrains+Mono:wght@400;500;600;700;800&family=Share+Tech+Mono&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --color-hacker-green: #00ff41;\n"
            + "  --color-hacker-dark: #080c09;\n"
            + "  --color-hacker-gray: #101912;\n"
            + "  --font-code: 'Courier Prime', 'Share Tech Mono', 'JetBrains Mono', 'Courier New', monospace;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "body, p, h1, h2, h3, h4, h5, h6, input, textarea, select, button, table, a, div {\n"
            + "  font-family: var(--font-code);\n"
            + "  -webkit-font-smoothing: antialiased;\n"
            + "  -moz-osx-font-smoothing: grayscale;\n"
            + "  text-rendering: optimizeLegibility;\n"
            + "}\n"
            + "\n"
            + "/* Ensure all icon fonts maintain their font glyphs and styling */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "  letter-spacing: normal !important;\n"
            + "}\n"
            + "\n"
            + "body {\n"
            + "  background-color: #080c09 !important;\n"
            + "  background-image: radial-gradient(rgba(0, 255, 65, 0.12) 1px, transparent 1px) !important;\n"
            + "  background-size: 24px 24px !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "  overflow-x: hidden;\n"
            + "  position: relative;\n"
            + "}\n"
            + "\n"
            + "/* Subtle Retro CRT Scanlines Effect */\n"
            + "body::before {\n"
            + "  content: ' ';\n"
            + "  display: block;\n"
            + "  position: fixed;\n"
            + "  top: 0; left: 0; bottom: 0; right: 0;\n"
            + "  background: linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.2) 50%);\n"
            + "  background-size: 100% 4px;\n"
            + "  z-index: 1;\n"
            + "  pointer-events: none;\n"
            + "  opacity: 0.3;\n"
            + "}\n"
            + "\n"
            + "/* Matrix Canvas Background Layer */\n"
            + "#matrix-rain-canvas {\n"
            + "  position: fixed;\n"
            + "  top: 0;\n"
            + "  left: 0;\n"
            + "  width: 100vw;\n"
            + "  height: 100vh;\n"
            + "  z-index: 0;\n"
            + "  pointer-events: none;\n"
            + "  opacity: 0.22;\n"
            + "}\n"
            + "\n"
            + "/* Matrix Custom Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #080c09; }\n"
            + "::-webkit-scrollbar-thumb { background: #005511; border-radius: 4px; border: 1px solid #00ff41; }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #00ff41; box-shadow: 0 0 10px #00ff41; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard {\n"
            + "  background-color: transparent !important;\n"
            + "  position: relative;\n"
            + "  z-index: 2;\n"
            + "}\n"
            + ".espresso-top, .jettra-topbar {\n"
            + "  background: rgba(8, 14, 10, 0.95) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-bottom: 1px solid rgba(0, 255, 65, 0.4) !important;\n"
            + "  box-shadow: 0 2px 20px rgba(0, 0, 0, 0.8), 0 0 15px rgba(0, 255, 65, 0.1) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  z-index: 10;\n"
            + "}\n"
            + ".espresso-left, .jettra-drawer {\n"
            + "  background: rgba(9, 15, 11, 0.95) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-right: 1px solid rgba(0, 255, 65, 0.3) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  z-index: 5;\n"
            + "}\n"
            + ".espresso-center, .jettra-main-viewport {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  z-index: 2;\n"
            + "}\n"
            + ".espresso-footer {\n"
            + "  background: rgba(8, 14, 10, 0.95) !important;\n"
            + "  backdrop-filter: blur(10px);\n"
            + "  -webkit-backdrop-filter: blur(10px);\n"
            + "  border-top: 1px solid rgba(0, 255, 65, 0.25) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  display: flex;\n"
            + "  justify-content: center;\n"
            + "  align-items: center;\n"
            + "}\n"
            + "\n"
            + "/* CyberShield Brand Logo */\n"
            + ".matrix-title, .sidebar-logo, .glitch {\n"
            + "  font-weight: 800 !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  text-shadow: 0 0 8px rgba(0, 255, 65, 0.7), 0 0 20px rgba(0, 255, 65, 0.3);\n"
            + "  transition: all 0.3s ease;\n"
            + "}\n"
            + ".matrix-title:hover, .glitch:hover {\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 12px #00ff41, 0 0 25px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Topbar Navigation Links (<TAG/> Style) */\n"
            + ".matrix-nav-link, .top-right-section a, .matrix-nav a {\n"
            + "  color: #00ff41 !important;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.85rem;\n"
            + "  letter-spacing: 0.15em;\n"
            + "  text-transform: uppercase;\n"
            + "  text-decoration: none;\n"
            + "  padding: 6px 12px;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + ".matrix-nav-link:hover, .top-right-section a:hover, .matrix-nav a:hover {\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 10px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Headings */\n"
            + "h1, h2, h3, h4, h5, h6, .espresso-panel-header, .stat-header {\n"
            + "  color: #00ff41 !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  text-shadow: 0 0 6px rgba(0, 255, 65, 0.4);\n"
            + "}\n"
            + "\n"
            + "/* High-Legibility Body Text */\n"
            + "p, span, div, li, td, th, label {\n"
            + "  color: #00ff66;\n"
            + "  line-height: 1.65;\n"
            + "  letter-spacing: 0.025em;\n"
            + "}\n"
            + "b, strong {\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 4px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Links */\n"
            + "a {\n"
            + "  color: #00ff41 !important;\n"
            + "  text-decoration: none;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + "a:hover {\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 8px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Navigation Links */\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #00ff66 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.25s ease;\n"
            + "  font-weight: 500;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  border: 1px solid transparent;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(0, 255, 65, 0.12) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-color: rgba(0, 255, 65, 0.3) !important;\n"
            + "  text-shadow: 0 0 8px #00ff41;\n"
            + "  transform: translateX(4px);\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background-color: rgba(0, 255, 65, 0.22) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-left: 3px solid #00ff41 !important;\n"
            + "  border-color: rgba(0, 255, 65, 0.5) !important;\n"
            + "  box-shadow: 0 0 14px rgba(0, 255, 65, 0.2);\n"
            + "  font-weight: 700;\n"
            + "}\n"
            + ".professional-left i, .espresso-left i, .top-right-section i, .jettra-hamburger {\n"
            + "  color: #00ff41 !important;\n"
            + "  text-shadow: 0 0 8px rgba(0, 255, 65, 0.7);\n"
            + "}\n"
            + "\n"
            + "/* Futuristic Hacker Buttons with High-Contrast Visible Text */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background-color: #00ff41 !important;\n"
            + "  color: #000000 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 14px rgba(0, 255, 65, 0.4) !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  padding: 10px 22px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + ".espresso-button *, .espresso-btn *, .btn *, .btn-primary * {\n"
            + "  color: #000000 !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-shadow: none !important;\n"
            + "}\n"
            + ".espresso-button i, .espresso-btn i, .btn i, .btn-primary i {\n"
            + "  color: #000000 !important;\n"
            + "  text-shadow: none !important;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background-color: #ffffff !important;\n"
            + "  border-color: #ffffff !important;\n"
            + "  box-shadow: 0 0 20px #00ff41 !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + ".espresso-button:hover *, .espresso-btn:hover *, .btn:hover *, .btn-primary:hover * {\n"
            + "  color: #000000 !important;\n"
            + "  text-shadow: none !important;\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: rgba(10, 16, 12, 0.8) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + ".espresso-btn-outlined *, .btn-outline-primary * {\n"
            + "  color: #00ff41 !important;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: rgba(0, 255, 65, 0.15) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-color: #ffffff !important;\n"
            + "  box-shadow: 0 0 15px #00ff41 !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + ".espresso-btn-outlined:hover *, .btn-outline-primary:hover * {\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + ".espresso-btn-secondary, .espresso-btn-secondary * {\n"
            + "  background-color: #122416 !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.4) !important;\n"
            + "}\n"
            + "\n"
            + "/* CyberShield Service Cards */\n"
            + ".espresso-card, .card, .espresso-panel {\n"
            + "  background: linear-gradient(180deg, #101912 0%, #09100a 100%) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.25) !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.7) !important;\n"
            + "  padding: 24px !important;\n"
            + "  transition: all 0.3s ease;\n"
            + "}\n"
            + ".espresso-card:hover, .card:hover, .espresso-card.active, .card.active {\n"
            + "  border-color: #00ff41 !important;\n"
            + "  box-shadow: 0 0 20px rgba(0, 255, 65, 0.25) !important;\n"
            + "}\n"
            + "\n"
            + "/* Icon Box inside Cards */\n"
            + ".matrix-icon-box, .stat-icon-box {\n"
            + "  width: 44px;\n"
            + "  height: 44px;\n"
            + "  border-radius: 8px;\n"
            + "  background: rgba(0, 255, 65, 0.08);\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.3);\n"
            + "  display: inline-flex;\n"
            + "  align-items: center;\n"
            + "  justify-content: center;\n"
            + "  margin-bottom: 18px;\n"
            + "  color: #00ff41;\n"
            + "  font-size: 1.25rem;\n"
            + "  transition: all 0.25s ease;\n"
            + "}\n"
            + ".espresso-card:hover .matrix-icon-box {\n"
            + "  background: rgba(0, 255, 65, 0.16);\n"
            + "  border-color: #00ff41;\n"
            + "  box-shadow: 0 0 12px rgba(0, 255, 65, 0.4);\n"
            + "}\n"
            + "\n"
            + "/* Learn More Action Link */\n"
            + ".matrix-learn-more {\n"
            + "  font-size: 0.8rem;\n"
            + "  font-weight: 700;\n"
            + "  color: #00ff41 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  display: inline-flex;\n"
            + "  align-items: center;\n"
            + "  gap: 6px;\n"
            + "  margin-top: 14px;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".matrix-learn-more:hover {\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 8px #00ff41;\n"
            + "  transform: translateX(4px);\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber, .form-control, .form-select, input, textarea, select {\n"
            + "  background-color: rgba(8, 14, 10, 0.95) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.45) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  caret-color: #00ff41 !important;\n"
            + "  padding: 10px 14px;\n"
            + "  font-size: 15px;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus, .form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #00ff41 !important;\n"
            + "  box-shadow: 0 0 14px rgba(0, 255, 65, 0.6) !important;\n"
            + "  outline: none !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: rgba(0, 255, 65, 0.45) !important;\n"
            + "}\n"
            + "option {\n"
            + "  background-color: #080c09 !important;\n"
            + "  color: #00ff41 !important;\n"
            + "}\n"
            + "\n"
            + "/* Tables */\n"
            + ".espresso-datatable, .espresso-table, .table {\n"
            + "  background: linear-gradient(180deg, #101912 0%, #09100a 100%) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.3) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th {\n"
            + "  background-color: rgba(6, 20, 10, 0.95) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border-bottom: 2px solid #00ff41 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "  padding: 12px 16px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td {\n"
            + "  border-bottom: 1px solid rgba(0, 255, 65, 0.18) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  padding: 12px 16px;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(0, 255, 65, 0.15) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 6px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Badges & Tags */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag, .matrix-pill {\n"
            + "  background-color: rgba(0, 255, 65, 0.15) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  border-radius: 4px !important;\n"
            + "  padding: 4px 10px;\n"
            + "  font-size: 0.8rem;\n"
            + "  font-weight: 700;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  box-shadow: 0 0 8px rgba(0, 255, 65, 0.25) !important;\n"
            + "}\n"
            + "\n"
            + "/* Modals & Dialogs */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content {\n"
            + "  background-color: rgba(10, 18, 12, 0.98) !important;\n"
            + "  border: 2px solid #00ff41 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 0 40px rgba(0, 255, 65, 0.45) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + "\n"
            + "/* Dropdown Menus */\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: rgba(10, 18, 12, 0.96) !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 25px rgba(0, 255, 65, 0.35) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #00ff66 !important;\n"
            + "  padding: 8px 16px;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: rgba(0, 255, 65, 0.2) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 8px #00ff41;\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "(function() {\n"
            + "  function initMatrixRain() {\n"
            + "    if (document.getElementById('matrix-rain-canvas')) return;\n"
            + "    var canvas = document.createElement('canvas');\n"
            + "    canvas.id = 'matrix-rain-canvas';\n"
            + "    document.body.prepend(canvas);\n"
            + "\n"
            + "    var ctx = canvas.getContext('2d');\n"
            + "    var w, h, cols, drops;\n"
            + "    var chars = '01アカサタナハマヤラワabcdefghijklmnopqrstuvwxyz1234567890ｦｱｳｴｵｶｷｹｺｻｼｽｾｿﾀﾂﾃﾅﾆﾇﾈﾊﾋﾎﾏﾐﾑﾒﾓﾔﾕﾗﾘﾜ+-*/=%\"#&_'.split('');\n"
            + "    var fontSize = 14;\n"
            + "\n"
            + "    function resize() {\n"
            + "      w = canvas.width = window.innerWidth;\n"
            + "      h = canvas.height = window.innerHeight;\n"
            + "      cols = Math.floor(w / fontSize) + 1;\n"
            + "      drops = [];\n"
            + "      for (var i = 0; i < cols; i++) {\n"
            + "        drops[i] = Math.floor(Math.random() * -50);\n"
            + "      }\n"
            + "    }\n"
            + "    resize();\n"
            + "    window.addEventListener('resize', resize);\n"
            + "\n"
            + "    var lastTime = 0;\n"
            + "    function render(time) {\n"
            + "      requestAnimationFrame(render);\n"
            + "      if (time - lastTime < 35) return; // ~30 fps cap\n"
            + "      lastTime = time;\n"
            + "\n"
            + "      ctx.fillStyle = 'rgba(8, 12, 9, 0.07)';\n"
            + "      ctx.fillRect(0, 0, w, h);\n"
            + "\n"
            + "      ctx.font = fontSize + 'px monospace';\n"
            + "      for (var i = 0; i < cols; i++) {\n"
            + "        var char = chars[Math.floor(Math.random() * chars.length)];\n"
            + "        var x = i * fontSize;\n"
            + "        var y = drops[i] * fontSize;\n"
            + "\n"
            + "        ctx.fillStyle = '#ffffff';\n"
            + "        ctx.shadowColor = '#00ff41';\n"
            + "        ctx.shadowBlur = 8;\n"
            + "        ctx.fillText(char, x, y);\n"
            + "\n"
            + "        ctx.fillStyle = '#00ff41';\n"
            + "        ctx.shadowBlur = 3;\n"
            + "        ctx.fillText(char, x, y - fontSize);\n"
            + "        ctx.shadowBlur = 0;\n"
            + "\n"
            + "        if (y > h && Math.random() > 0.975) {\n"
            + "          drops[i] = 0;\n"
            + "        } else {\n"
            + "          drops[i]++;\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "    requestAnimationFrame(render);\n"
            + "  }\n"
            + "  if (document.readyState === 'loading') {\n"
            + "    document.addEventListener('DOMContentLoaded', initMatrixRain);\n"
            + "  } else {\n"
            + "    initMatrixRain();\n"
            + "  }\n"
            + "})();\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".matrix-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".matrix-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .matrix-dashboard-grid, .matrix-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: linear-gradient(180deg, #101912 0%, #09100a 100%) !important; border: 1px solid rgba(0, 255, 65, 0.25) !important; border-radius: 12px !important; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.7) !important; padding: 24px; transition: all 0.3s ease; }\n"
            + ".stat-card:hover { border-color: #00ff41 !important; box-shadow: 0 0 18px rgba(0, 255, 65, 0.25) !important; }\n"
            + ".stat-header { font-size: 0.85rem; color: #00ff41 !important; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; }\n"
            + ".stat-value { font-size: 2.2rem; font-weight: 700; color: #ffffff !important; text-shadow: 0 0 12px #00ff41; }\n"
            + ".stat-badge { padding: 4px 10px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; display: inline-flex; align-items: center; gap: 4px; border: 1px solid currentColor; letter-spacing: 0.05em; }\n"
            + ".stat-badge.down { background-color: rgba(239, 68, 68, 0.2) !important; color: #ff5555 !important; border-color: rgba(239, 68, 68, 0.5) !important; }\n"
            + ".stat-badge.up { background-color: rgba(0, 255, 65, 0.18) !important; color: #00ff41 !important; border-color: #00ff41 !important; box-shadow: 0 0 8px rgba(0, 255, 65, 0.3); }\n"
            + "</style>";
    }
}
