package io.jettra.flux.theme;

/**
 * SLTheme provides a futuristic virtual world aesthetic inspired by Second Life (Linden Lab).
 *
 * Visual Signature:
 * - Second Life iconic Linden Green (#84cf29) as primary brand action color
 * - Virtual Sky Cyan (#00bcd4 / #1ea7fd) teleport accents
 * - Deep virtual world midnight slate canvas (#0e131d / #131926)
 * - Translucent viewer floater panels (#1a2233 / #222d42)
 * - Coordinate chips and Linden Dollar badges (L$)
 */
public class SLTheme {

    public static ThemeData create() {
        return SL.create();
    }

    public static ThemeData create(ColorMode mode) {
        return SL.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return SL.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* SL (Second Life) Theme Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@500;600;700&family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --sl-green: #84cf29;\n"
            + "  --sl-green-hover: #99e63a;\n"
            + "  --sl-cyan: #00bcd4;\n"
            + "  --sl-orange: #ff8500;\n"
            + "  --sl-dark-bg: #0e131d;\n"
            + "  --sl-floater-surface: #1a2233;\n"
            + "  --sl-floater-header: #141b29;\n"
            + "  --sl-border: rgba(132, 207, 41, 0.25);\n"
            + "  --background-color: #0e131d !important;\n"
            + "  --surface-color: #1a2233 !important;\n"
            + "  --on-surface-color: #f1f5f9 !important;\n"
            + "  --on-primary-color: #0e131d !important;\n"
            + "  --primary-color: #84cf29 !important;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "/* Preserve icon font families */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "}\n"
            + "\n"
            + "/* Virtual World Background Canvas */\n"
            + "html, body {\n"
            + "  background-color: #0e131d !important;\n"
            + "  background-image: \n"
            + "    radial-gradient(at 15% 15%, rgba(132, 207, 41, 0.07) 0px, transparent 45%),\n"
            + "    radial-gradient(at 85% 85%, rgba(0, 188, 212, 0.08) 0px, transparent 50%) !important;\n"
            + "  background-attachment: fixed !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "}\n"
            + "\n"
            + "/* SL Custom Glow Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #0e131d; }\n"
            + "::-webkit-scrollbar-thumb { background: #26334d; border-radius: 4px; border: 1px solid rgba(132, 207, 41, 0.2); }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #84cf29; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard, .espresso-center, .espresso-main, .jettra-main-viewport, .professional-center {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + ".espresso-top, .jettra-topbar {\n"
            + "  background: rgba(20, 27, 41, 0.94) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-bottom: 1px solid rgba(132, 207, 41, 0.25) !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  z-index: 10;\n"
            + "}\n"
            + ".espresso-left, .jettra-drawer {\n"
            + "  background: rgba(20, 27, 41, 0.96) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-right: 1px solid rgba(132, 207, 41, 0.2) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  z-index: 5;\n"
            + "}\n"
            + ".espresso-footer {\n"
            + "  background: #141b29 !important;\n"
            + "  border-top: 1px solid rgba(132, 207, 41, 0.2) !important;\n"
            + "  color: #94a3b8 !important;\n"
            + "  display: flex;\n"
            + "  justify-content: center;\n"
            + "  align-items: center;\n"
            + "}\n"
            + "\n"
            + "/* Second Life Sidebar Logo & Category */\n"
            + ".sidebar-logo {\n"
            + "  color: #84cf29 !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  font-size: 1.3rem;\n"
            + "  letter-spacing: 0.1em;\n"
            + "  text-shadow: 0 0 10px rgba(132, 207, 41, 0.5);\n"
            + "}\n"
            + ".sidebar-category {\n"
            + "  color: #00bcd4 !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-size: 0.8rem;\n"
            + "  font-weight: 700;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.12em;\n"
            + "}\n"
            + "\n"
            + "/* Navigation Links (SL Viewer Menu Style) */\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #94a3b8 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 500;\n"
            + "  border: 1px solid transparent;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(132, 207, 41, 0.12) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-color: rgba(132, 207, 41, 0.3) !important;\n"
            + "  transform: translateX(4px);\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background: linear-gradient(90deg, rgba(132, 207, 41, 0.25) 0%, rgba(0, 188, 212, 0.15) 100%) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-left: 3px solid #84cf29 !important;\n"
            + "  border-color: rgba(132, 207, 41, 0.4) !important;\n"
            + "  font-weight: 700;\n"
            + "  box-shadow: 0 0 14px rgba(132, 207, 41, 0.2);\n"
            + "}\n"
            + ".professional-left i, .espresso-left i, .top-right-section i, .jettra-hamburger {\n"
            + "  color: #84cf29 !important;\n"
            + "}\n"
            + ".professional-left a.active i, .espresso-left a.active i {\n"
            + "  color: #84cf29 !important;\n"
            + "  text-shadow: 0 0 8px #84cf29;\n"
            + "}\n"
            + "\n"
            + "/* Second Life Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background: linear-gradient(135deg, #84cf29 0%, #68a620 100%) !important;\n"
            + "  color: #0e131d !important;\n"
            + "  border: none !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  box-shadow: 0 0 12px rgba(132, 207, 41, 0.35) !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-button *, .espresso-btn *, .btn *, .btn-primary * {\n"
            + "  color: #0e131d !important;\n"
            + "  font-weight: 800 !important;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background: #99e63a !important;\n"
            + "  box-shadow: 0 0 18px rgba(132, 207, 41, 0.6) !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #84cf29 !important;\n"
            + "  border: 1px solid #84cf29 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-btn-outlined *, .btn-outline-primary * {\n"
            + "  color: #84cf29 !important;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: rgba(132, 207, 41, 0.2) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-color: #84cf29 !important;\n"
            + "  box-shadow: 0 0 14px rgba(132, 207, 41, 0.4) !important;\n"
            + "}\n"
            + ".espresso-btn-secondary, .espresso-btn-secondary * {\n"
            + "  background-color: #222d42 !important;\n"
            + "  color: #00bcd4 !important;\n"
            + "  border: 1px solid rgba(0, 188, 212, 0.4) !important;\n"
            + "}\n"
            + "\n"
            + "/* Viewer Floaters (Cards & Panels) */\n"
            + ".espresso-card, .card, .espresso-panel,\n"
            + "[class*=\"bg-white\"], [class*=\"bg-light\"], .bg-white, .bg-light {\n"
            + "  background-color: #1a2233 !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid rgba(132, 207, 41, 0.22) !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5) !important;\n"
            + "  padding: 24px;\n"
            + "}\n"
            + ".espresso-panel-header {\n"
            + "  background: linear-gradient(90deg, #141b29 0%, #172338 100%) !important;\n"
            + "  color: #84cf29 !important;\n"
            + "  border-bottom: 1px solid rgba(132, 207, 41, 0.25) !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-size: 1.1rem;\n"
            + "  font-weight: 700;\n"
            + "  padding: 14px 20px;\n"
            + "  letter-spacing: 0.05em;\n"
            + "}\n"
            + "\n"
            + "/* Headings & Text */\n"
            + "h1, h2, h3, h4, h5, h6, .top-dashboard-title, .stat-value, .chart-card-header, strong, b {\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  letter-spacing: 0.02em;\n"
            + "}\n"
            + "p, span, label, td, li, .tx-details, .stat-header, .tx-date {\n"
            + "  color: #cbd5e1;\n"
            + "}\n"
            + "small {\n"
            + "  color: #94a3b8 !important;\n"
            + "}\n"
            + ".text-dark, .text-black, [class*=\"text-dark\"], [class*=\"text-black\"] {\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber,\n"
            + ".form-control, .form-select, input, textarea, select {\n"
            + "  background-color: #121824 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid #2d3d59 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px;\n"
            + "  font-size: 14px;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus,\n"
            + ".form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #84cf29 !important;\n"
            + "  box-shadow: 0 0 0 3px rgba(132, 207, 41, 0.25) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: #64748b !important;\n"
            + "}\n"
            + "option, select option {\n"
            + "  background-color: #121824 !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Datatables */\n"
            + ".espresso-datatable, .espresso-table, .table, table {\n"
            + "  background-color: #1a2233 !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "  border: 1px solid rgba(132, 207, 41, 0.2) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th, thead th {\n"
            + "  background-color: #141b29 !important;\n"
            + "  color: #00bcd4 !important;\n"
            + "  border-bottom: 1px solid rgba(132, 207, 41, 0.25) !important;\n"
            + "  font-family: 'Rajdhani', sans-serif !important;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.85rem;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "  padding: 12px 16px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td, tbody td {\n"
            + "  border-bottom: 1px solid rgba(255, 255, 255, 0.05) !important;\n"
            + "  color: #cbd5e1 !important;\n"
            + "  background-color: transparent !important;\n"
            + "  padding: 14px 16px;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(132, 207, 41, 0.08) !important;\n"
            + "}\n"
            + "\n"
            + "/* SL Coordinate / Linden Dollar Badges */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag {\n"
            + "  background-color: rgba(132, 207, 41, 0.15) !important;\n"
            + "  color: #84cf29 !important;\n"
            + "  border: 1px solid rgba(132, 207, 41, 0.35) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 3px 8px;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-family: 'JetBrains Mono', monospace !important;\n"
            + "}\n"
            + "\n"
            + "/* Modals & Dialogs */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content, .modal {\n"
            + "  background-color: #1a2233 !important;\n"
            + "  border: 1px solid rgba(132, 207, 41, 0.35) !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 20px 35px rgba(0, 0, 0, 0.7) !important;\n"
            + "  color: #f1f5f9 !important;\n"
            + "}\n"
            + "\n"
            + "/* Dropdowns */\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: #1a2233 !important;\n"
            + "  border: 1px solid rgba(132, 207, 41, 0.25) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.6) !important;\n"
            + "  color: #cbd5e1 !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #cbd5e1 !important;\n"
            + "  padding: 10px 16px;\n"
            + "  border-radius: 6px;\n"
            + "  transition: all 0.15s ease;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: rgba(132, 207, 41, 0.15) !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Tabs & Accordions */\n"
            + ".espresso-tabview-nav { border-bottom: 2px solid rgba(132, 207, 41, 0.25) !important; }\n"
            + ".espresso-tabview-nav-link { color: #94a3b8 !important; }\n"
            + ".espresso-tabview-nav-link:hover { color: #ffffff !important; }\n"
            + ".espresso-tabview-nav-active .espresso-tabview-nav-link { color: #84cf29 !important; border-bottom: 2px solid #84cf29 !important; }\n"
            + ".espresso-divider-content { background-color: #1a2233 !important; color: #94a3b8 !important; }\n"
            + ".espresso-divider { border-color: rgba(132, 207, 41, 0.2) !important; }\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "function toggleSidebar() {\n"
            + "  var sidebar = document.querySelector('.espresso-left');\n"
            + "  if(sidebar) sidebar.classList.toggle('open');\n"
            + "}\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".sl-dashboard-grid, .oceantheme-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".sl-main-grid, .oceantheme-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .sl-dashboard-grid, .sl-main-grid, .oceantheme-dashboard-grid, .oceantheme-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: #1a2233 !important; border: 1px solid rgba(132, 207, 41, 0.25) !important; border-radius: 12px !important; box-shadow: 0 8px 24px rgba(0,0,0,0.5) !important; padding: 22px; }\n"
            + ".stat-header { font-size: 0.85rem; color: #00bcd4 !important; font-weight: 700; font-family: 'Rajdhani', sans-serif !important; text-transform: uppercase; letter-spacing: 0.08em; }\n"
            + ".stat-value { font-size: 2.2rem; font-weight: 800; color: #ffffff !important; }\n"
            + ".stat-badge { padding: 4px 10px; border-radius: 6px; font-size: 0.75rem; font-weight: 700; display: inline-flex; align-items: center; gap: 4px; font-family: 'JetBrains Mono', monospace; }\n"
            + ".stat-badge.down { background-color: rgba(239, 68, 68, 0.15) !important; color: #f87171 !important; border: 1px solid rgba(239, 68, 68, 0.3) !important; }\n"
            + ".stat-badge.up { background-color: rgba(132, 207, 41, 0.15) !important; color: #84cf29 !important; border: 1px solid rgba(132, 207, 41, 0.35) !important; }\n"
            + "</style>";
    }
}
