package io.jettra.server.config;

import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * Automatically generates the jcf.AppRole enum from jettra-config.properties.
 */
public class AppRoleGenerator {

    public static void generateFromProperties(Properties properties) {
        String rolesProp = properties != null ? properties.getProperty("app.roles") : null;
        generate(rolesProp);
    }

    public static void generate(String rolesProp) {
        List<String> rolesList = new ArrayList<>();
        if (rolesProp != null && !rolesProp.trim().isEmpty()) {
            String[] parts = rolesProp.split(",");
            for (String part : parts) {
                String trimmed = part.trim().toUpperCase();
                if (!trimmed.isEmpty() && !rolesList.contains(trimmed)) {
                    rolesList.add(trimmed);
                }
            }
        }

        if (rolesList.isEmpty()) {
            rolesList.add("ADMIN");
            rolesList.add("MANAGER");
            rolesList.add("USER");
        }

        StringBuilder code = new StringBuilder();
        code.append("package jcf;\n\n");
        code.append("/**\n");
        code.append(" * Auto-generated by JettraAppServer from jettra-config.properties.\n");
        code.append(" */\n");
        code.append("public enum AppRole {\n");

        for (int i = 0; i < rolesList.size(); i++) {
            code.append("    ").append(rolesList.get(i));
            if (i < rolesList.size() - 1) {
                code.append(",");
            } else {
                code.append(";");
            }
            code.append("\n");
        }

        code.append("\n    public String getValue() {\n");
        code.append("        return name();\n");
        code.append("    }\n");
        code.append("}\n");

        writeToProjectSource(code.toString());
    }

    private static void writeToProjectSource(String content) {
        Path srcDir = Paths.get("src/main/java/jcf");
        try {
            if (Files.exists(Paths.get("src/main/java"))) {
                Files.createDirectories(srcDir);
                Path file = srcDir.resolve("AppRole.java");
                if (Files.exists(file)) {
                    String existing = Files.readString(file, StandardCharsets.UTF_8);
                    if (existing.equals(content)) {
                        return; // Up to date, do not re-touch file
                    }
                }
                Files.writeString(file, content, StandardCharsets.UTF_8);
                System.out.println("[JettraAppServer] Automatically generated/updated jcf.AppRole (" + file.toAbsolutePath() + ")");
            }
        } catch (Exception e) {
            System.err.println("[JettraAppServer] Failed to generate jcf.AppRole: " + e.getMessage());
        }
    }
}
