<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

<!--    <groupId>io.jettra</groupId>
    <artifactId>JettraRest</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jettra.annotation.version>1.0.0-SNAPSHOT</jettra.annotation.version>
        <jettra.jwt.version>1.0.0-SNAPSHOT</jettra.jwt.version>
        <jettra.ee.version>1.0.0-SNAPSHOT</jettra.ee.version>
        <jettra.json.version>1.0.0-SNAPSHOT</jettra.json.version>
    </properties>-->
<parent>
        <groupId>io.jettra</groupId>
        <artifactId>jettraframeworks</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <!-- 2. Identificador del Submódulo -->
    <artifactId>JettraRest</artifactId>
    <packaging>jar</packaging>
    <name>JettraRest</name>
    <description>Módulo JettraRest para el ecosistema Jettra</description>

    <dependencies>
        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraJSON</artifactId> 
            <scope>provided</scope>
        </dependency>
        <!-- Jettra Server core -->
        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraAppServer</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraJWT</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraAnnotation</artifactId>

            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraCDI</artifactId>

            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.1.1</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

</project>
